---
- name: Install nginx
  hosts: maven
  become: yes

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    - name: edit index.html is present
      lineinfile:
        path: /var/www/html/index.html
        regexp: 'nginx'
        line: <h1><p><script> document.write(new Date().toLocaleDateString());</script></p></h1>
